### ISSUE TITLE
Android storage on v3 branch

### ISSUE THREAD

**Issue by kyle-ssg** [fullstackreact/react-native-firestack#150]
Hey @Salakar , this may be linked to the conversation in https://github.com/fullstackreact/react-native-firestack/pull/109 however I didn't want to hijack the thread in case it wasn't.

Thanks for for all the work put in - everything so far is working fantastic except android storage. I gave this a go on the v3 branch - database worked without any changes however storage seems to throw an exception:

```
11-20 14:26:01.013  4089  5584 I FirestackStorage: From file: /storage/emulated/0/DCIM/Camera/IMG_20161120_131408.jpg to gs://project-4251246165915577329.appspot.com with name img

11-20 14:26:01.014  4089  5584 I System.out: Transferred 0.0/5175.0(0.0% complete)

11-20 14:26:01.014  4089  5584 I System.out: Transferred 0.0/5175.0(0.0% complete)

11-20 14:26:01.014  4089  5894 W GooglePlayServicesUtil: Google Play Store is missing.

11-20 14:26:01.014  4089  5894 W DynamiteModule: Local module descriptor class for com.google.android.gms.firebasestorage not found.

11-20 14:26:01.014  4089  5894 I DynamiteModule: Considering local module com.google.android.gms.firebasestorage:0 and remote module com.google.android.gms.firebasestorage:0

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: NetworkRequestFactoryProxy failed with a RemoteException:

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: com.google.android.gms.internal.zztl$zza: No acceptable module found. Local version is 0 and remote version is 0.

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zztl.zza(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zztl.zza(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zzaol.<init>(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zzaol.zzj(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.StorageReference.an(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.UploadTask.aA(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.UploadTask.run(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.StorageTask$8.run(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at java.lang.Thread.run(Thread.java:818)

11-20 14:26:01.014  4089  5894 E UploadTask: Unable to create a network request from metadata
```

Code to attempt upload was as follows

```
		var storage = firebase.storage();
		storage.setStorageUrl(Project.firebase.storageBucket)
		storage.uploadFile("img", file.uri, {
			contentType: 'image/jpeg',
			contentEncoding: 'base64',
		})
			.then((res) => alert('The file has been uploaded'))
			.catch(err => console.error('There was an error uploading the file', err))
```

Is there something I'm doing wrong, or perhaps that this won't work without google play services under simulator? Thanks.

**Comment by kyle-ssg** [comment]
Can confirm that this issue was due to google play services not being installed on genymotion. The above code works fine once this is installed. Thanks again

**Comment by Ehesp** [comment]
I believe some checks are going to go in at some point to check for required services being installed.

**Comment by Salakar** [comment]
@Ehesp @kyle-ssg yep I've done some work to detect and alert if play services is missing - will push this up Monday =]

**Comment by kyle-ssg** [comment]
Great stuff! Will be keeping an eye out for when v3 gets merged :)
