### ISSUE TITLE
Android Verifier rejected  due to bad method 

### ISSUE THREAD

**Issue by neuberoliveira** [fullstackreact/react-native-firestack#333]
I have been testing the app only in the IOS simulator and it works nicely, my problem is, now i need to test it on android, but as soon the app start it immediately close with the stacktrace bellow, and i dont have any idea why.

```
04-18 14:44:04.717 16168-16168/br.com.dopaminamob.upark I/art: Thread[1,tid=16168,WaitingForJniOnLoad,Thread*=0xf421c000,peer=0x740b6f50,"main"] recursive attempt to load library "/data/app/br.com.dopaminamob.upark-2/lib/x86/libfb.so"
04-18 14:44:04.720 16168-16168/br.com.dopaminamob.upark W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
04-18 14:44:04.950 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
04-18 14:44:04.954 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
04-18 14:44:04.959 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
04-18 14:44:04.962 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
04-18 14:44:04.963 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
04-18 14:44:04.967 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
04-18 14:44:04.976 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
04-18 14:44:04.978 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
04-18 14:44:04.980 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
04-18 14:44:04.983 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
04-18 14:44:04.984 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
04-18 14:44:04.987 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
04-18 14:44:04.992 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
04-18 14:44:04.994 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
04-18 14:44:04.995 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
04-18 14:44:04.997 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
04-18 14:44:04.998 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
04-18 14:44:05.002 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
04-18 14:44:05.008 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
04-18 14:44:05.011 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
04-18 14:44:05.013 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
04-18 14:44:05.014 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
04-18 14:44:05.015 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
04-18 14:44:05.016 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
04-18 14:44:05.016 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
04-18 14:44:05.018 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
04-18 14:44:05.027 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
04-18 14:44:05.029 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
04-18 14:44:05.030 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
04-18 14:44:05.034 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
04-18 14:44:05.038 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
04-18 14:44:05.040 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
04-18 14:44:05.041 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
04-18 14:44:05.044 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
04-18 14:44:05.046 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
04-18 14:44:05.048 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.BV.LinearGradient.LinearGradientManager
04-18 14:44:05.050 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapCalloutManager
04-18 14:44:05.052 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapMarkerManager
04-18 14:44:05.056 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapPolylineManager
04-18 14:44:05.058 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapPolygonManager
04-18 14:44:05.061 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapCircleManager
04-18 14:44:05.064 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapManager
04-18 14:44:05.070 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapLiteManager
04-18 14:44:05.071 16168-16683/br.com.dopaminamob.upark W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapUrlTileManager
04-18 14:44:05.160 16168-16683/br.com.dopaminamob.upark D/OAuthManager: New instance
04-18 14:44:05.162 16168-16683/br.com.dopaminamob.upark D/Firestack: New instance
04-18 14:44:05.171 16168-16683/br.com.dopaminamob.upark D/FirestackAuth: New FirestackAuth instance
04-18 14:44:05.179 16168-16683/br.com.dopaminamob.upark D/FirestackAnalytics: New instance
04-18 14:44:05.188 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzg>
04-18 14:44:05.188 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzg>
04-18 14:44:05.189 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzb>
04-18 14:44:05.190 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzb>
04-18 14:44:05.192 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.192 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.192 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzb>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.193 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.194 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzc>
04-18 14:44:05.194 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzc>
04-18 14:44:05.195 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzc>
04-18 14:44:05.197 16168-16683/br.com.dopaminamob.upark I/art: Verification error in com.google.android.gms.internal.zzaso com.google.android.gms.internal.zzatp.zzJg()
04-18 14:44:05.197 16168-16683/br.com.dopaminamob.upark I/art: com.google.android.gms.internal.zzaso com.google.android.gms.internal.zzatp.zzJg() failed to verify: register v0 has type Reference: com.google.android.gms.internal.zzaso but expected Reference: com.google.android.gms.internal.zzatr
04-18 14:44:05.198 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zze>
04-18 14:44:05.199 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzd>
04-18 14:44:05.199 16168-16683/br.com.dopaminamob.upark I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzd>
04-18 14:44:05.204 16168-16683/br.com.dopaminamob.upark E/art: Verification failed on class com.google.android.gms.internal.zzatp in /data/app/br.com.dopaminamob.upark-2/split_lib_dependencies_apk.apk:classes32.dex because: Verifier rejected class com.google.android.gms.internal.zzatp due to bad method com.google.android.gms.internal.zzaso com.google.android.gms.internal.zzatp.zzJg()
                                                               
                                                               --------- beginning of crash
04-18 14:44:05.205 16168-16683/br.com.dopaminamob.upark E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                          Process: br.com.dopaminamob.upark, PID: 16168
                                                                          java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.lang.VerifyError: Verifier rejected class com.google.android.gms.internal.zzatp due to bad method com.google.android.gms.internal.zzaso com.google.android.gms.internal.zzatp.zzJg() (declaration of 'com.google.android.gms.internal.zzatp' appears in /data/app/br.com.dopaminamob.upark-2/split_lib_dependencies_apk.apk:classes32.dex)
                                                                              at com.google.android.gms.internal.zzatp.zzbu(Unknown Source)
                                                                              at com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)
                                                                              at io.fullstack.firestack.FirestackAnalyticsModule.<init>(FirestackAnalytics.java:42)
                                                                              at io.fullstack.firestack.FirestackPackage.createNativeModules(FirestackPackage.java:31)
                                                                              at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:955)
                                                                              at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:879)
                                                                              at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
                                                                              at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
                                                                              at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                              at java.lang.Thread.run(Thread.java:818) 
```

thanks

**Comment by neuberoliveira** [comment]
in fact this was caused by another problem,and i think theres nothing to do with this repo. sorry.
