### ISSUE TITLE
Ask - Unable to find a specification for `Firebase` when linking modules

### ISSUE THREAD

**Issue by yogieputra8** [fullstackreact/react-native-firestack#71]
So I try to created a new RN project, then I installed firestack module `npm install react-native-firestack --save`, everythings worked fine from here.
But when I tried to linking the modules with `react-native link react-native-firestack`,
Somethings goes wrong
```
Yogies-MacBook-Pro:firestack_app yogieputra$ react-native link react-native-firestack
Preparing to link react-native-firestack for iOS
Checking CocoaPods...
CocoaPods already installed
rnpm-install info Linking react-native-firestack android dependency 
rnpm-install info Android module react-native-firestack has been successfully linked 
rnpm-install info Linking react-native-firestack ios dependency 
rnpm-install info iOS module react-native-firestack has been successfully linked 
Checking Podfile in iOS project (/Users/yogieputra/Works/firestack_app/ios/Podfile)
Adding Podfile to iOS project
Installing Pods
Analyzing dependencies
[!] Unable to find a specification for `Firebase`
/Users/yogieputra/Works/firestack_app/node_modules/react-native/local-cli/core/makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node_modules/react-native-firestack/bin/cocoapods.sh" command
    at ChildProcess.prelink (/Users/yogieputra/Works/firestack_app/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
Can you guys help me how to solve this issue?
Sorry for this silly questions

**Comment by yogieputra8** [comment]
Ah! I forget to install the firebase module before install this firestack.
Maybe it's a good idea to give an explanation on the **README** about having firebase module before install this firestack. IMO

**Comment by dondragon2** [comment]
What were the exact steps that you used because it is still failing for me after I installed the firebase module `npm uninstall --save firebase`
